[[car_parks]]
name = "carpark1"
location = "Moondaloop Park"
host = "localhost"
port = 1883
topic-root = "carpark1"
total_bays = 5

[[car_parks.sensors]]
name = "sensor1"
location = "L306"
type = "entry"

[[car_parks.sensors]]
name = "sensor2"
location = "L306"
type = "exit"

[[car_parks.displays]]
name = "display1"

# -----------------------------------------------

[[car_parks]]
name = "carpark2"
location = "Jandurah Park"
host = "localhost"
port = 1883
topic-root = "carpark2"
total_bays = 1

[[car_parks.sensors]]
name = "sensor1"
location = "L250"
type = "entry"

[[car_parks.sensors]]
name = "sensor2"
location = "L250"
type = "exit"

[[car_parks.displays]]
name = "display1"

[[car_parks.displays]]
name = "display2"